<meta charset="utf-8" />

<title>{{ project_title }}</title>
<link rel="stylesheet" href="assets/css/main.css" />
<link rel="stylesheet" href="assets/css/overwrite.css" />
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,500,700' rel='stylesheet' type='text/css'>
<meta name="viewport" content="width=device-width">
<meta content="IE=edge, chrome=1" http-equiv="X-UA-Compatible">

<link href="{{ shortcutIcon.url }}" rel="shortcut icon">
